- name: Massage
  description: I was impresed by the moling services, not lorem ipsum is simply free text.
  img: assets/images/services/services-1-2.jpg
  icon: icon-massage
  url: book
- name: Facial Care
  description: I was impresed by the moling services, not lorem ipsum is simply free text.
  img: assets/images/services/services-1-1.jpg
  icon: icon-facial-mask
  url: book
- name: Hydro Therapy
  description: I was impresed by the moling services, not lorem ipsum is simply free text.
  img: assets/images/services/services-1-3.jpg
  icon: icon-lotus
  url: book
- name: Massage
  description: I was impresed by the moling services, not lorem ipsum is simply free text.
  img: assets/images/services/services-1-2.jpg
  icon: icon-massage
  url: book
- name: Facial Care
  description: I was impresed by the moling services, not lorem ipsum is simply free text.
  img: assets/images/services/services-1-1.jpg
  icon: icon-facial-mask
  url: book
- name: Hydro Therapy
  description: I was impresed by the moling services, not lorem ipsum is simply free text.
  img: assets/images/services/services-1-3.jpg
  icon: icon-lotus
  url: book